update

diff --git a/01 makefile toturial.txt b/01 makefile toturial.txt
--- a/01 makefile toturial.txt
+++ b/01 makefile toturial.txt
@@ -193,4 +193,148 @@ thing_right := $(wildcard *.o)
 
 all: one two three four
 
-# Fails, because $(thing_wrong) is the string 
+# Fails, because $(thing_wrong) is the string "*.o"
+one: $(thing_wrong)
+
+# Stays as *.o if there are no files that match this pattern :(
+two: *.o
+
+# Works as you would expect! In this case, it does nothing.
+three: $(thing_right)
+
+# Same as rule three
+four: $(wildcard *.o)
+
+% Wildcard 
+% is really useful, but is somewhat confusing because of the variety of situations it can be used in.
+	- When used in "matching" mode, it matches one or more characters in a string. This match is called the stem.
+	- When used in "replacing" mode, it takes the stem that was matched and replaces that in a string.
+	- % is most often used in rule definitions and in some specific functions.
+See these sections on examples of it being used:
+
+	Static Pattern Rules
+	Pattern Rules
+	String Substitution (thay thế chuỗi)
+	The vpath Directive
+
+Automatic Variables
+There are many automatic variables, but often only few show uo:
+
+hey: one two
+	#Outputs "hey", since this is the target name
+	echo $@
+
+	# Outputs all prerequisites newer than the target
+	echo $?
+	
+	# Outputs all prerequisites
+	echo $^
+	touch hey
+
+one:
+	touch one
+two:
+	touch two
+
+clean:
+	rm -f hey one two
+
+Fancy Rules
+Implicit Rules
+
+Make loves c compilatin. And every time it expresss its love, things get confusing. Perhaps the most confusing part of Make is
+the magic/automatic rules that are made. Make calls these "implicit" rules. I don't personally agree with  this design decision, and I
+don't recommend using them, but they're often used and are thus useful to know. Here's a list of implicit rule:
+	Compiling a C program: n.o is made automatically from n.c with a command of the form $(CC) -c $(CPPFLAGS) $(CFLAGS) $^ -o $@
+	Compiling a C++ program: n.o is made automatically from n.cc or n.cpp with a command of the form $(CXX) -x $(CPPFLAGS) $(CXXFLAGS) $^ -o $@
+	Linking a single object file: n is made automatically from n.o by running the command $(CC) $(LDFLAGS) $^ $(LOADLIBES) $(LDLIBS) -o $@
+The important variables used by implicit rules are:
+	CC: Program for compiling C programs: default cc
+	CXX: Program for compiling C++ programs: default g++
+	CLAGS: Extra flags to give to the C compiler
+	CXXFLAGS: Extra flags to give to the C++ compiler
+	CPPFLAGS: Extra flags to give the C preprocessor
+	LDFLAGS: Extra flags to give to compilers when they are supposed to invoke the linked
+
+Let's see how we can now build a C program without ever explicitly teelling Make how to do the compilation:
+CC = gcc # Flag for implicit rules
+CFLAG = -g # Flag for implicit rules. Turn on debug info
+
+#Implicit rule #1: blah is built via the C linker implicit rule
+#Implicit rule #2: blah.o is build via the compilation implicit rule, because blah.c exists
+blah: blah.o
+
+blah.c:
+	echo "int main() {return 0;}" > blah.c
+clean:
+	rm -f blah*
+
+Static pattern Rules
+Statc pattern rules are another way to write less in a Makefiel. Here's their syntax:
+targets...: target-pattern: prered-patterns ...
+	command
+The essence is that the given target is matched by the target-pattern (via a % wildcard). Whatever was matched is called the stem. The stem is then substituted
+into the prereq-pattern, to generate the target's prereqs.
+
+A typical use case is to compile .c file into .o files. Here's the manual way:
+objects = foo.o bar.o all.o
+all: $(objects)
+	$(CC) $^ -o all
+foo.o: foo.c
+	$(CC) -c foo.c -o foo.o
+bar.o: bar.c
+	$(CC) -c bar.c -o bar.o
+all.o: all.c
+	$(CC) -c all.c -o all.o
+
+all.c:
+	echo "int main() { return 0; }" > all.c
+# Note: all.c does not use this rule because Make prioritizes more specific matches when there is more than one match.
+%.c:
+	touch $@
+clean:
+	rm -f *.c *.o all
+
+Here's the more efficient way, using a static pattern rule:
+objects = foo.o bar.o all.o
+all: $(objects)
+	$(CC) $^ -o all
+
+# Syntax - targets ...: target-pattern: prereq-patterns ...
+# In the case of the first target, foo.o, the target-pattern matches foo.o and sets the "stem" to be foo.o
+# It then replaces the '%' in prereq-patterns with that stem
+
+$(objects): %.o: %.c
+	$(CC) -c $^ -o $@
+
+all.c
+	echo "int main() {return 0;}" > all.c
+
+# Note: all.c does not use this rule because Make prioritizes more specific matches when there is more than one match.
+%.c:
+	touch $@
+
+clean:
+	rm -f *.c *.o all
+Here's the more efficient way, using a static pattern rule:
+objects = foo.o bar.o all.o
+all: $(objects)
+	$(CC) $^ -o all
+# Syntax - targets ...: target-pattern: prereq-patterns ...
+# In the case of the first target, foo.o, the target-pattern matches foo.o and sets the "stem" to be "foo.o".
+# It then replaces the '%' in prereq-patterns with that stem
+$(objects): %.o: %.c
+	$(CC) -c $^ -o $@
+
+all.c:
+	echo "int main() {return 0; } > all.c
+
+# Note: all.c does not use this rule because Make prioritizes more specific matches when there is more than one match.
+%.c:
+	touch $@
+clean:
+	rm -f *.c *.o all
+
+Static Pattern Rules and Filter
+While I introduce the filter function later on, It's common to use in static pattern rules, so I'll mention that here. 
+The filter function can be used in Static pattern rules to match the correct files. In this example, I made up the .raw
